"""Client for the patched NetHack 3.6.7 "bot" window port.

One `Engine` = one game process in its own directory.  The engine speaks the
JSON-lines protocol documented in engine/nethack-3.6.7/win/bot/winbot.c:
every input the game needs arrives as a request (`Request`), and exactly one
answer line is written back.

The engine keeps the accumulated observation (map, status, inventory) so the
caller only deals with requests.  Evaluation-only data (`priv`, the end
verdict) is kept apart from what a policy should see.
"""
import json
import os
import shutil
import signal
import subprocess
import time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INSTALL = os.path.join(ROOT, 'build', 'install')
NHDIR = os.path.join(INSTALL, 'nhdir')
BINARY = os.path.join(NHDIR, 'nethack')

ROWNO, COLNO = 21, 80

HOW_NAMES = ["died", "choked", "poisoned", "starved", "drowned", "burned",
             "dissolved", "crushed", "stoned", "slimed", "genocided",
             "panicked", "tricked", "quit", "escaped", "ascended"]

DEFAULT_OPTIONS = [
    "windowtype:bot",
    "role:valkyrie", "race:dwarf", "gender:female", "align:lawful",
    "!autopickup", "pickup_types:$", "pickup_burden:unencumbered",
    "!bones", "!legacy", "!news", "!mail", "!tombstone", "!splash_screen",
    "disclose:-i -a -v -g -c -o",
    "time", "showexp", "!cmdassist", "!autodescribe", "!dark_room",
    "lit_corridor", "mention_walls", "number_pad:0", "runmode:teleport",
    "!sparkle", "sortloot:n", "paranoid_confirmation:none",
    "suppress_alert:3.4.3", "menustyle:partial", "!rest_on_space",
    "!autoquiver", "pettype:none",
    # objects/zaps carry their color only with use_color (mapglyph.c); a
    # colorless iron chain "_" was taken for an altar (full-w02 g004)
    "color",
    # NB: keep "verbose" on: BotHack's prompt/message regexes were written
    # for verbose texts ("Dip the long sword into the fountain?" rather than
    # "Dip it into the fountain?")
]


class EngineError(Exception):
    pass


class EngineEOF(EngineError):
    """The game process closed the protocol channel."""


class Request(object):
    __slots__ = ('seq', 'kind', 'raw', 'events', 'query', 'choices',
                 'default', 'prompt', 'how', 'items', 'goal', 'cx', 'cy')

    def __init__(self, raw):
        self.raw = raw
        self.seq = raw.get('seq')
        self.kind = raw.get('kind')
        self.events = raw.get('ev') or []
        self.query = raw.get('query')
        self.choices = raw.get('choices')
        self.default = raw.get('default')
        self.prompt = raw.get('prompt')
        self.how = raw.get('how')
        self.items = raw.get('items')
        self.goal = raw.get('goal')
        self.cx = raw.get('cx')
        self.cy = raw.get('cy')

    def messages(self):
        return [e[1] for e in self.events if e and e[0] == 'msg']

    def __repr__(self):
        return "<Request #%s %s %r>" % (self.seq, self.kind,
                                        self.query or self.prompt or '')


def prepare_gamedir(gamedir, wizard=False, options=None, name='bot'):
    """Create an isolated NetHack directory (level files, xlogfile, dumplog)
    for one game.  Returns the path of the config file to use."""
    nhdir = os.path.join(gamedir, 'nhdir')
    os.makedirs(os.path.join(nhdir, 'save'), exist_ok=True)
    for f in ('nhdat', 'license', 'symbols'):
        dst = os.path.join(nhdir, f)
        if not os.path.exists(dst):
            os.symlink(os.path.join(NHDIR, f), dst)
    for f in ('perm', 'record', 'logfile', 'xlogfile'):
        open(os.path.join(nhdir, f), 'a').close()
    with open(os.path.join(nhdir, 'sysconf'), 'w') as f:
        f.write("# generated by nhbot.engine\n")
        f.write("WIZARDS=%s\n" % ('*' if wizard else 'nobody-at-all'))
        f.write("EXPLORERS=nobody-at-all\n")
        f.write("MAXPLAYERS=0\n")
        f.write("PANICTRACE_LIBC=0\nPANICTRACE_GDB=0\n")
        f.write("DUMPLOGFILE=%s\n" % os.path.join(nhdir, 'dumplog.txt'))
        f.write("POINTSMIN=1\nENTRYMAX=100\nPERSMAX=100\n")
    rc = os.path.join(gamedir, 'nethackrc')
    opts = list(DEFAULT_OPTIONS if options is None else options)
    opts.append("name:%s" % name)
    with open(rc, 'w') as f:
        for o in opts:
            f.write("OPTIONS=%s\n" % o)
    return rc


class Engine(object):
    """A running game.  Typical use:

        eng = Engine(gamedir, env={...}).start()
        req = eng.next_request()
        while req is not None:
            eng.answer(...)
            req = eng.next_request()
        eng.verdict  # engine end record, or None
    """

    def __init__(self, gamedir, seed=None, wizard=False, assists=None,
                 options=None, name='bot', binary=BINARY, trace=None):
        self.gamedir = os.path.abspath(gamedir)
        self.seed = seed
        self.wizard = wizard
        self.assists = dict(assists or {})
        self.options = options
        self.name = name
        self.binary = binary
        self.trace = trace          # file object receiving raw protocol lines
        self.proc = None
        self.hello = None
        self.verdict = None
        self.bye = None
        self.req = None
        self.map_glyph = [[-2] * COLNO for _ in range(ROWNO)]
        self.map_ch = [[32] * COLNO for _ in range(ROWNO)]
        self.map_color = [[0] * COLNO for _ in range(ROWNO)]
        self.map_special = [[0] * COLNO for _ in range(ROWNO)]
        self.status = {}
        self.priv = {}
        self.inventory = []
        self.u = (0, 0)
        self.curs = (0, 0)
        self.assist_events = []
        self.protoerrs = []
        self.nreq = 0
        self.stderr_path = None
        self.start_time = None

    # ----------------------------------------------------------- lifecycle
    def start(self):
        rc = prepare_gamedir(self.gamedir, self.wizard, self.options,
                             self.name)
        nhdir = os.path.join(self.gamedir, 'nhdir')
        game_r, bot_w = os.pipe()     # game reads fd 3
        bot_r, game_w = os.pipe()     # game writes fd 4
        env = dict(os.environ)
        for k in list(env):
            if k.startswith('NH_') or k in ('NETHACKOPTIONS', 'HACKDIR'):
                del env[k]
        env['NETHACKDIR'] = nhdir
        env['NETHACKOPTIONS'] = rc
        env['HOME'] = self.gamedir
        env['NH_ASSIST_LOG'] = os.path.join(self.gamedir, 'assist.jsonl')
        if self.seed is not None:
            env['NH_SEED'] = str(int(self.seed))
        for k, v in self.assists.items():
            if k == 'NH_ASSIST_KIT' and v:
                v = os.path.abspath(v)
            env[k] = str(v)
        args = [self.binary]
        if self.wizard:
            args.append('-D')
        self.stderr_path = os.path.join(self.gamedir, 'engine.stderr')
        errf = open(self.stderr_path, 'ab')

        env['NH_BOT_IN_FD'] = str(game_r)
        env['NH_BOT_OUT_FD'] = str(game_w)
        self.proc = subprocess.Popen(
            args, cwd=nhdir, env=env, stdin=subprocess.DEVNULL,
            stdout=errf, stderr=errf, pass_fds=(game_r, game_w),
            start_new_session=True, close_fds=True)
        errf.close()
        os.close(game_r)
        os.close(game_w)
        self._w = os.fdopen(bot_w, 'w', buffering=1)
        self._r = os.fdopen(bot_r, 'r', buffering=1 << 16)
        self.start_time = time.time()
        return self

    def stop(self, timeout=5.0):
        if self.proc is None:
            return
        try:
            self._w.close()
        except Exception:
            pass
        try:
            self.proc.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            try:
                os.killpg(self.proc.pid, signal.SIGKILL)
            except Exception:
                self.proc.kill()
            self.proc.wait()
        try:
            self._r.close()
        except Exception:
            pass

    @property
    def returncode(self):
        return None if self.proc is None else self.proc.poll()

    # ------------------------------------------------------------ protocol
    def _readline(self):
        line = self._r.readline()
        if not line:
            raise EngineEOF("engine closed the channel (rc=%s)"
                            % self.proc.poll())
        if self.trace is not None:
            self.trace.write(line)
        return json.loads(line)

    def next_request(self):
        """Read until the next input request.  Returns None when the game is
        over (verdict/bye received and channel closed)."""
        while True:
            try:
                msg = self._readline()
            except EngineEOF:
                self.req = None
                return None
            t = msg.get('t')
            if t == 'req':
                self._absorb(msg)
                self.req = Request(msg)
                self.nreq += 1
                return self.req
            elif t == 'hello':
                self.hello = msg
            elif t == 'end':
                self.verdict = msg
            elif t == 'bye':
                self.bye = msg
                for e in msg.get('ev') or []:
                    self._event(e)
            else:
                raise EngineError("unknown message %r" % (msg,))

    def _event(self, e):
        if not e:
            return
        if isinstance(e, dict) and e.get('t') == 'end':
            self.verdict = self.verdict or e
        elif e[0] == 'assist':
            self.assist_events.append(e[1])
        elif e[0] == 'protoerr':
            self.protoerrs.append(e[1:])

    def _absorb(self, msg):
        for e in msg.get('ev') or []:
            self._event(e)
        for x, y, g, ch, col, sp in msg.get('map') or ():
            self.map_glyph[y][x] = g
            self.map_ch[y][x] = ch
            self.map_color[y][x] = col
            self.map_special[y][x] = sp
        if 'st' in msg:
            self.status = msg['st']
        if 'priv' in msg:
            self.priv = msg['priv']
        if 'inv' in msg:
            self.inventory = msg['inv']
        if 'u' in msg:
            self.u = tuple(msg['u'])
        if 'curs' in msg:
            self.curs = tuple(msg['curs'])

    def _send(self, line):
        if '\n' in line:
            raise EngineError("newline in answer %r" % line)
        if self.trace is not None:
            self.trace.write("> " + line + "\n")
        try:
            self._w.write(line + "\n")
            self._w.flush()
        except BrokenPipeError:
            raise EngineEOF("engine gone while answering")

    # answers ------------------------------------------------------------
    def key(self, ch):
        code = ch if isinstance(ch, int) else ord(ch)
        self._send("k %d" % code)

    def yn(self, ch, number=None):
        code = ch if isinstance(ch, int) else ord(ch)
        self._send("y %d" % code if number is None
                   else "y %d %d" % (code, number))

    def line(self, text):
        self._send("l " + text)

    def ext(self, name):
        self._send("x " + name)

    def menu(self, picks):
        """picks: iterable of item ids or (id, count) pairs"""
        parts = []
        for p in picks:
            if isinstance(p, tuple):
                parts.append("%d:%d" % p)
            else:
                parts.append("%d" % p)
        self._send("m " + " ".join(parts) if parts else "m")

    def pos(self, x, y):
        self._send("p %d %d" % (x, y))

    def escape(self):
        self._send("e")

    # helpers -----------------------------------------------------------
    def screen_lines(self):
        """ASCII rendering of the map (rows 1..21 of a tty)."""
        return ["".join(chr(c) if 32 <= c < 127 else '?' for c in row)
                for row in self.map_ch]


def read_xlogfile(gamedir):
    """Parse the per-game xlogfile written by NetHack itself."""
    path = os.path.join(gamedir, 'nhdir', 'xlogfile')
    out = []
    if not os.path.exists(path):
        return out
    with open(path, errors='replace') as f:
        for line in f:
            line = line.rstrip('\n')
            if not line:
                continue
            rec = {}
            for field in line.split('\t'):
                if '=' in field:
                    k, v = field.split('=', 1)
                    rec[k] = v
            out.append(rec)
    return out


def cleanup_level_files(gamedir):
    """Remove bulky level/lock files, keep logs."""
    nhdir = os.path.join(gamedir, 'nhdir')
    if not os.path.isdir(nhdir):
        return
    for f in os.listdir(nhdir):
        p = os.path.join(nhdir, f)
        if '.' in f and f.split('.')[-1].isdigit() or f.endswith('lock'):
            try:
                os.remove(p)
            except OSError:
                pass
    save = os.path.join(nhdir, 'save')
    if os.path.isdir(save) and not os.listdir(save):
        shutil.rmtree(save, ignore_errors=True)
