#!/bin/bash
# mapidx X0 X1: print map rows 11-29 between columns X0..X1 with column ruler (x as in Map features)
cd "$(dirname "$0")"
./v | sed -n '/^1[0-9] \|^2[0-9] \|^0[0-9] /p' | python3 -c "
import sys
a,b=int(sys.argv[1]),int(sys.argv[2])
for l in sys.stdin:
    y=int(l[:2]); row=l[4:]
    if y<10: continue
    print('%2d '%y+''.join(row[x] if x<len(row) else ' ' for x in range(a,b+1)))
print('   '+''.join(str(x//10%10) for x in range(a,b+1)))
print('   '+''.join(str(x%10) for x in range(a,b+1)))
" ${1:-1} ${2:-79}
